kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "nginx"
spec:
  template:
    metadata:
      name: "nginx"
      namespace: "shared"
      labels:
        app: "nginx"
        deploymentconfig: "nginx"
    spec:
      containers:
        - name: "nginx"
          image: "nginx"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: "TCP"
          env:
          - name: DB_HOST
            value: "my.db.host.com"
          - name: DB_PORT
            value: "3306"
          - name: DB_DRIVER
            value: "mysql+pymysql"
          - name: DB_USER
            value: "my_db_user"
          - name: DB_PASSWORD
            value: "my_db_password"
          - name: DB_NAME
            value: "my_db_name"
          - name: DB_DEBUG
            value: "no"
      dnsPolicy: ClusterFirst
  replicas: 1
  selector:
    app: "nginx"
    deploymentconfig: "nginx"
  triggers:
    - type: "ConfigChange"
  strategy:
    type: "Rolling"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "nginx"
  name: "nginx"
  namespace: "shared"
spec:
  ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 80
  selector:
    app: "nginx"
    deploymentconfig: "nginx"
status:
  loadBalancer: {}

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: shared
spec:
  host: nginx.it-fullservice.eu
  port:
    targetPort: 8000-tcp
  to:
    kind: Service
    name: nginx
    weight: 100
  wildcardPolicy: None